'use client';

import {
  PlaneTakeoff,
  Monitor,
  Plane,
  Gamepad2,
  BookOpen,
  Library,
  Globe,
  Globe2,
  HelpCircle,
  Wrench,
  Map,
  MessageCircle,
  Video,
  Glasses,
  Headphones,
  BarChart3,
  Target,
  Smartphone,
  Ruler,
  RotateCcw,
  RefreshCw,
  MapPin,
  Mic,
  Clock,
  ArrowLeft,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  X,
  Play,
  Pause,
  Rewind,
  FastForward,
  Check,
  CircleX,
  Download,
  Eye,
  Info,
  Search,
  Folder,
  ClipboardList,
  CheckSquare,
  Compass,
  AlertTriangle,
  CloudSun,
  PlaneLanding,
  Settings,
  Radio,
  Building2,
  Flame,
  Timer,
  TrendingUp,
  GraduationCap,
  Trophy,
  Waves,
  Sprout,
  Sparkles,
  Newspaper,
  Calendar,
  User,
  Volume2,
  Zap,
  FileText,
  PartyPopper,
  Award,
  Crosshair,
  ScanEye,
  Star,
  RotateCw,
  Clipboard,
  BookMarked,
} from 'lucide-react';

const ICONS = {
  planeTakeoff: PlaneTakeoff,
  monitor: Monitor,
  plane: Plane,
  gamepad2: Gamepad2,
  bookOpen: BookOpen,
  library: Library,
  globe: Globe,
  world: Globe2,
  helpCircle: HelpCircle,
  wrench: Wrench,
  map: Map,
  messageCircle: MessageCircle,
  video: Video,
  glasses: Glasses,
  headphones: Headphones,
  barChart3: BarChart3,
  target: Target,
  smartphone: Smartphone,
  ruler: Ruler,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  refreshCw: RefreshCw,
  mapPin: MapPin,
  mic: Mic,
  clock: Clock,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  x: X,
  play: Play,
  pause: Pause,
  rewind: Rewind,
  fastForward: FastForward,
  check: Check,
  circleX: CircleX,
  download: Download,
  eye: Eye,
  info: Info,
  search: Search,
  folder: Folder,
  clipboardList: ClipboardList,
  clipboard: Clipboard,
  checkSquare: CheckSquare,
  compass: Compass,
  alertTriangle: AlertTriangle,
  cloudSun: CloudSun,
  planeLanding: PlaneLanding,
  settings: Settings,
  radio: Radio,
  building2: Building2,
  flame: Flame,
  timer: Timer,
  trendingUp: TrendingUp,
  graduationCap: GraduationCap,
  trophy: Trophy,
  waves: Waves,
  sprout: Sprout,
  sparkles: Sparkles,
  newspaper: Newspaper,
  calendar: Calendar,
  user: User,
  volume2: Volume2,
  zap: Zap,
  fileText: FileText,
  partyPopper: PartyPopper,
  award: Award,
  crosshair: Crosshair,
  scanEye: ScanEye,
  star: Star,
  bookMarked: BookMarked,
};

/**
 * @param {{ name: keyof typeof ICONS; size?: number; className?: string; strokeWidth?: number }} props
 */
export function IconByName({ name, size = 20, className, strokeWidth = 2, ...rest }) {
  const Icon = ICONS[name];
  if (!Icon) return null;
  return <Icon size={size} className={className} strokeWidth={strokeWidth} aria-hidden {...rest} />;
}

export { ICONS };
